{{- if eq .Values.service.type "NodePort" }}
{{- if eq .Values.tls "external" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname"-grpc . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  type: clusterIP
  selector:
    app: {{ template "rancher.fullname" . }}
{{- end }}
{{- end }}
